name: WebGoat Sonatype Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      JAVA_HOME: /opt/homebrew/Cellar/openjdk@25/25.0.4.1/libexec/openjdk.jdk/Contents/Home

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Java
        run: |
          java -version
          ./mvnw -v

      - name: Build WebGoat
        run: |
          ./mvnw clean package -DskipTests -P!start-server

      - name: Sonatype Lifecycle Evaluation
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: http://localhost:8070
          username: ${{ secrets.LIFECYCLE_USERNAME }}
          password: ${{ secrets.LIFECYCLE_PASSWORD }}
          application-id: webgoatgithub
          scan-targets: target/*.jar
